### PR TITLE
Add geo point and geo polygon

### PR DESCRIPTION
**Pull request by javiercr**
Completes the work started in #24

* Fixed implementation for Geo.Point
* Added Geo.Polygon
* Make :geo dependency optional
* Fixed merge conflicts

### CODE REVIEW

**Comment by fuelen** [comment]
Hey @javiercr 

Thank you for the PR.
It would be great if you resolve this comment as well https://github.com/fuelen/ecto_dev_logger/pull/24#discussion_r1306650312
For both: point and polygon.

**Comment by javiercr** [comment]
> Hey @javiercr
> 
> Thank you for the PR. It would be great if you resolve this comment as well [#24 (comment)](https://github.com/fuelen/ecto_dev_logger/pull/24#discussion_r1306650312) For both: point and polygon.

hey @fuelen! happy to contribute!

That comment was already addressed, I changed the implementation and the test to make sure the generated output is actually valid for a SQL query.

https://github.com/fuelen/ecto_dev_logger/pull/32/files#diff-37460eec3684bc654e8ad968483d8c355ff711a71895f05fb84a3b2732639edeR94-R99

Am I missing anything else?

Thanks!

**Comment by fuelen** [comment]
@javiercr I asked ChatGPT how to convert a polygon and point from tests to text and it responded me with
```sql
ST_GeomFromText('POLYGON((2.20 41.41, 2.13 41.41, 2.13 41.35, 2.20 41.35, 2.20 41.41))', 4326)
ST_GeomFromText('POINT(44.21587 -87.5947)', 4326)
```
So I expected something like this in the implementation. However, quick googling points to https://stackoverflow.com/a/49905336 which shows that representation in JSON is one of the options.

Just want to confirm: do polygon and point represented as JSON work fine if we copy and paste generated SQL query to psql?

**Comment by javiercr** [comment]
Uhm, I'm no expert in postgis, but AFAIK geo_postgis (which I think is the de-facto standard to work with Postgis in Elixir) uses JSON:

```
# When a binary is passed to `Geo.PostGIS.Geometry.cast/1` implementation of
# `Ecto.Type.cast/1`, it is assumed to be a GeoJSON string. When this happens,
# geo_postgis will use Poison, by default, to convert the binary to a map and
# then convert that map to one of the Geo structs. If in these cases you would
# like to use a different JSON parser, you can set the config below.
```


https://github.com/felt/geo_postgis/tree/b9f03a9ab1e5eea9f7ee2b8f2ee6559beee2bb3c?tab=readme-ov-file#optional-configuration

> Just want to confirm: do polygon and point represented as JSON work fine if we copy and paste generated SQL query to psql?

Yes it does! (at least for everything I've tested in my app, using postgis and my fork of ecto_dev_logger)

**Comment by fuelen** [comment]
> Yes it does! (at least for everything I've tested in my app, using postgis and my fork of ecto_dev_logger)

Then I'm happy to merge the PR :slightly_smiling_face: Thank you for the contribution!

**Comment by fuelen** [comment]
Available in v0.12.0 :tada:

**Pull request merged**
